=== elyra-ai/canvas/canvas_modules/common-canvas/src/object-model/schemas/v2/pipeline-flow-v2-schema.json
{
  "$schema": "https://json-schema.org/draft-04/schema#",
  "description": "WDP Pipeline Flow Schema",
  "type": "object",
  "id": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v2-schema.json",
  "properties": {
    "doc_type": {
      "description": "Document type",
      "type": "string"
    },
    "version": {
      "description": "Pipeline-flow schema version",
      "enum": [
        "2.0"
      ]
    },
    "json_schema": {
      "description": "Refers to the JSON schema used to validate documents of this type",
      "enum": [
        "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v2-schema.json"
      ]
    },
    "open_with_tool": {
      "description": "Preferred authoring application",
      "type": "string"
    },
    "id": {
      "description": "Document identifier, GUID recommended",
      "type": "string"
    },
    "parameters": {
      "description": "Parameters for the flow document",
      "type": "object",
      "properties": {},
      "additionalProperties": true
    },
    "primary_pipeline": {
      "description": "Reference to the primary (main) pipeline flow within the document",
      "type": "string"
    },
    "pipelines": {
      "description": "Array of pipelines",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/pipeline_def"
      },
      "uniqueItems": true
    },
    "schemas": {
      "description": "Array of data record schemas used in the document",
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/datarecord-metadata/datarecord-metadata-v2-schema.json#/definitions/record_schema"
      },
      "uniqueItems": true
    },
    "runtimes": {
      "description": "Array of runtime objects referred to in the document",
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "#/definitions/runtime_def"
      },
      "uniqueItems": true
    },
    "external_parameters": {
      "description": "Array of parameterized property references",
      "type": "array",
      "minItems": 0,
      "items": {
        "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/parameters/parameters-v2-schema.json#/definitions/param_property_ref"
      },
      "uniqueItems": true
    },
    "app_data": {
      "$ref": "#/definitions/app_data_def"
    }
  },
  "required": [
    "doc_type",
    "version",
    "primary_pipeline",
    "pipelines"
  ],
  "additionalProperties": false,
  "definitions": {
    "pipeline_def": {
      "description": "Definition of a single pipeline flow",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier",
          "type": "string"
        },
        "name": {
          "description": "User-readable name",
          "type": "string"
        },
        "runtime_ref": {
          "description": "Reference to the id of the runtime associated with the operations in the current pipeline",
          "type": "string"
        },
        "nodes": {
          "description": "Array of pipeline nodes",
          "type": "array",
          "minItems": 0,
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/node_def"
              },
              {
                "$ref": "#/definitions/supernode_def"
              },
              {
                "$ref": "#/definitions/binding_entry_node_def"
              },
              {
                "$ref": "#/definitions/binding_exit_node_def"
              },
              {
                "$ref": "#/definitions/model_node_def"
              }
            ]
          },
          "uniqueItems": true
        },
        "parameters": {
          "description": "Parameters for the pipeline",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "runtime_ref",
        "nodes"
      ],
      "additionalProperties": false
    },
    "node_def": {
      "description": "Definition of a single pipeline node",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for node within the current pipeline",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'execution_node' for non-model pipeline elements",
          "enum": [
            "execution_node"
          ]
        },
        "op": {
          "description": "Operator type identifier",
          "type": "string"
        },
        "inputs": {
          "$ref": "#/definitions/ports_def"
        },
        "outputs": {
          "$ref": "#/definitions/ports_def"
        },
        "parameters": {
          "description": "Input parameters for the operator",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        },
        "runtime_ref": {
          "description": "Optional reference to the id of the runtime associated with the current node",
          "type": "string"
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "type",
        "op"
      ],
      "additionalProperties": false
    },
    "supernode_def": {
      "description": "Definition of a supernode which serves as the entry point for a sub-pipeline",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for the supernode within the current pipeline",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'super_node' for supernode elements",
          "enum": [
            "super_node"
          ]
        },
        "open_with_tool": {
          "description": "Name of the tool which can be used to view or edit the sub-flow for this supernode. The default is 'canvas'",
          "type": "string"
        },
        "subflow_ref": {
          "description": "Refers to the sub-flow associated with this supernode",
          "type": "object",
          "properties": {
            "url": {
              "description": "Reference to an external sub-flow. When not present the sub-flow is assumed to be in the current document. A value of 'app_defined' indicates a sub-flow identifier is present, but the controlling application will serve up the sub-pipeline in the form of a new pipeline-flow document (no sub-flow is present in the document).",
              "type": "string"
            },
            "pipeline_id_ref": {
              "description": "Sub-flow identifier reference",
              "type": "string"
            }
          },
          "required": [
            "pipeline_id_ref"
          ]
        },
        "inputs": {
          "$ref": "#/definitions/bound_ports_def"
        },
        "outputs": {
          "$ref": "#/definitions/bound_ports_def"
        },
        "parameters": {
          "description": "Input parameters for the supernode",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "type",
        "subflow_ref",
        "inputs"
      ],
      "additionalProperties": false
    },
    "binding_entry_node_def": {
      "description": "Defines an entry point (source) for a pipeline. Bindings can be concrete: the concrete_binding element is present on the port; or bindings can be abstract: bindings are performed externally via configuration or a wrapper document.",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for the binding within the current pipeline",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'binding' for binding elements",
          "enum": [
            "binding"
          ]
        },
        "outputs": {
          "$ref": "#/definitions/ports_def"
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        },
        "connection": {
          "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-connection/pipeline-connection-v2-schema.json#/definitions/common_pipeline_connection_def"
        },
        "data_asset": {
          "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-connection/pipeline-connection-v2-schema.json#/definitions/common_pipeline_data_asset_def"
        },
        "op": {
          "description": "Binding node type identifier",
          "type": "string"
        },
        "parameters": {
          "description": "Parameters for the entry binding node",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        }
      },
      "required": [
        "id",
        "type"
      ],
      "additionalProperties": false
    },
    "binding_exit_node_def": {
      "description": "Defines an exit point (sink) for a pipeline. Bindings can be concrete: the concrete_binding element is present on the port; or bindings can be abstract: bindings are performed externally via configuration or a wrapper document.",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for the binding within the current pipeline",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'binding' for binding elements",
          "enum": [
            "binding"
          ]
        },
        "inputs": {
          "$ref": "#/definitions/ports_def"
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        },
        "connection": {
          "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-connection/pipeline-connection-v2-schema.json#/definitions/common_pipeline_connection_def"
        },
        "data_asset": {
          "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-connection/pipeline-connection-v2-schema.json#/definitions/common_pipeline_data_asset_def"
        },
        "op": {
          "description": "Binding node type identifier",
          "type": "string"
        },
        "parameters": {
          "description": "Parameters for the binding exit node",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        }
      },
      "required": [
        "id",
        "type"
      ],
      "additionalProperties": false
    },
    "model_node_def": {
      "description": "Definition of a single predictive model node",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier for the model within the current pipeline",
          "type": "string"
        },
        "type": {
          "description": "Node type - always 'model_node' for model pipeline elements",
          "enum": [
            "model_node"
          ]
        },
        "model_ref": {
          "description": "Reference to the binary model",
          "type": "string"
        },
        "inputs": {
          "$ref": "#/definitions/ports_def"
        },
        "outputs": {
          "$ref": "#/definitions/ports_def"
        },
        "parameters": {
          "description": "Input parameters for the operator",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        },
        "runtime_ref": {
          "description": "Reference to the runtime associated with the current node",
          "type": "string"
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "type",
        "inputs"
      ],
      "additionalProperties": false
    },
    "port_def": {
      "description": "Port definition (input/output) on a node",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier",
          "type": "string"
        },
        "schema_ref": {
          "description": "Optional data record schema reference associated with the port",
          "type": "string"
        },
        "links": {
          "description": "Array of links going into the node. Applies to input ports and exit bindings only.",
          "type": "array",
          "minItems": 0,
          "items": {
            "$ref": "#/definitions/link_def"
          },
          "uniqueItems": true
        },
        "parameters": {
          "description": "Parameters for the port",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "ports_def": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/port_def"
      },
      "uniqueItems": true
    },
    "bound_ports_def": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/bound_port_def"
      },
      "uniqueItems": true
    },
    "bound_port_def": {
      "description": "Port definition (input/output) on a node with optional pipeline port binding for supernodes",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique identifier",
          "type": "string"
        },
        "schema_ref": {
          "description": "Optional data record schema associated with the port",
          "type": "string"
        },
        "links": {
          "description": "Array of links going into the node. Applies to input ports and exit bindings only.",
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/link_def"
          },
          "uniqueItems": true
        },
        "subflow_node_ref": {
          "description": "Optional node id binding within the current document.",
          "type": "string"
        },
        "parameters": {
          "description": "Parameters for the binding port",
          "type": "object",
          "properties": {},
          "additionalProperties": true
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "link_def": {
      "description": "Node link definition",
      "type": "object",
      "properties": {
        "node_id_ref": {
          "description": "id of a node this link connects to",
          "type": "string"
        },
        "port_id_ref": {
          "description": "optional port id of a node this link connects to",
          "type": "string"
        },
        "link_name": {
          "description": "optional link name (used in parameter sets when there are multiple input sources)",
          "type": "string"
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "node_id_ref"
      ],
      "additionalProperties": false
    },
    "app_data_def": {
      "description": "Object containing app-specific data",
      "type": "object",
      "properties": {
        "ui_data": {
          "anyOf": [
            {
              "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-ui-v2-schema.json#/definitions/pipeline_overview_def"
            },
            {
              "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-ui-v2-schema.json#/definitions/pipeline_def"
            },
            {
              "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-ui-v2-schema.json#/definitions/port_info_def"
            },
            {
              "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-ui-v2-schema.json#/definitions/node_info_def"
            },
            {
              "$ref": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-ui-v2-schema.json#/definitions/runtime_info_def"
            }
          ]
        }
      },
      "additionalProperties": true
    },
    "runtime_def": {
      "description": "Runtime associated with the operations in the current pipeline",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique internal runtime identifier",
          "type": "string"
        },
        "name": {
          "description": "The runtime name",
          "type": "string"
        },
        "version": {
          "description": "The runtime version. When not present the latest version is assumed",
          "type": "string"
        },
        "app_data": {
          "$ref": "#/definitions/app_data_def"
        }
      },
      "required": [
        "id",
        "name"
      ]
    }
  }
}

=== elyra-ai/canvas/canvas_modules/harness/test_resources/diagrams/v2-uiParametersCanvas.json
{
  "doc_type": "pipeline",
  "version": "2.0",
  "json_schema": "https://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v2-schema.json",
  "id": "blank-canvas-id",
  "primary_pipeline": "empty-pipeline",
  "pipelines": [
    {
      "id": "empty-pipeline",
      "nodes": [
        {
          "id": "a9d5c402-2dba-4766-b854-37cbdcac8770",
          "type": "execution_node",
          "op": "sparkSelectColumns_paramDef",
          "app_data": {
            "ui_data": {
              "label": "Select Columns",
              "image": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOS4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjE4IC0xOC4yIDUyLjIgNTIuMiIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAxOCAtMTguMiA1Mi4yIDUyLjI7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+DQoJLnN0MHtmaWxsOiNFQUVBRUE7fQ0KCS5zdDF7ZmlsbDojREZERkRGO30NCgkuc3Qye2ZpbGw6bm9uZTtzdHJva2U6IzFEMzY0OTtzdHJva2Utd2lkdGg6MjtzdHJva2UtbWl0ZXJsaW1pdDoxMDt9DQoJLnN0M3tmaWxsOm5vbmU7c3Ryb2tlOiMxRDM2NDk7c3Ryb2tlLXdpZHRoOjM7c3Ryb2tlLW1pdGVybGltaXQ6MTA7fQ0KCS5zdDR7b3BhY2l0eTowLjU7ZmlsbDpub25lO3N0cm9rZTojMUQzNjQ5O3N0cm9rZS13aWR0aDozO3N0cm9rZS1taXRlcmxpbWl0OjEwO30NCgkuc3Q1e2ZpbGw6I0U3MUQzMjt9DQo8L3N0eWxlPg0KPGc+DQoJDQoJCTxpbWFnZSBzdHlsZT0ib3ZlcmZsb3c6dmlzaWJsZTtvcGFjaXR5OjAuNjY7IiB3aWR0aD0iNTQiIGhlaWdodD0iNDciIHhsaW5rOmhyZWY9IkJBOTI2N0EyRjgxNjk1QzIucG5nIiAgdHJhbnNmb3JtPSJtYXRyaXgoMSAwIDAgMSAxOCAtMTYpIj4NCgk8L2ltYWdlPg0KCTxnPg0KCQk8cG9seWdvbiBjbGFzcz0ic3QwIiBwb2ludHM9IjMyLjEsMjYgMjAuNCw1LjUgMzIuMSwtMTUgNTUuNiwtMTUgNjcuNCw1LjUgNTUuNiwyNiAJCSIvPg0KCTwvZz4NCjwvZz4NCjxwb2x5Z29uIGNsYXNzPSJzdDEiIHBvaW50cz0iMjksMjAuNSAzMi4xLDI2IDU1LjYsMjYgNjcuNCw1LjUgNTguNiwtOS42ICIvPg0KPGc+DQoJDQoJCTxpbWFnZSBzdHlsZT0ib3ZlcmZsb3c6dmlzaWJsZTtvcGFjaXR5OjAuNjY7IiB3aWR0aD0iNTYiIGhlaWdodD0iNDkiIHhsaW5rOmhyZWY9IkJBOTI2N0EyRjgxNjk1QzYucG5nIiAgdHJhbnNmb3JtPSJtYXRyaXgoMSAwIDAgMSAxNyAtMTcpIj4NCgk8L2ltYWdlPg0KCTxnPg0KCQk8cG9seWdvbiBjbGFzcz0ic3QyIiBwb2ludHM9IjMyLjEsMjYgMjAuNCw1LjUgMzIuMSwtMTUgNTUuNiwtMTUgNjcuNCw1LjUgNTUuNiwyNiAJCSIvPg0KCTwvZz4NCjwvZz4NCjxsaW5lIGNsYXNzPSJzdDMiIHgxPSI1My41IiB5MT0iLTIiIHgyPSI1My41IiB5Mj0iMTYiLz4NCjxsaW5lIGNsYXNzPSJzdDQiIHgxPSI0NC41IiB5MT0iLTIiIHgyPSI0NC41IiB5Mj0iMSIvPg0KPGxpbmUgY2xhc3M9InN0NCIgeDE9IjQ0LjUiIHkxPSItNiIgeDI9IjQ0LjUiIHkyPSItNCIvPg0KPGxpbmUgY2xhc3M9InN0MyIgeDE9IjM1LjUiIHkxPSItNiIgeDI9IjM1LjUiIHkyPSItNCIvPg0KPGxpbmUgY2xhc3M9InN0MyIgeDE9IjUzLjUiIHkxPSItNiIgeDI9IjUzLjUiIHkyPSItNCIvPg0KPGxpbmUgY2xhc3M9InN0NCIgeDE9IjQ0LjUiIHkxPSI5IiB4Mj0iNDQuNSIgeTI9IjE2Ii8+DQo8bGluZSBjbGFzcz0ic3QzIiB4MT0iMzUuNSIgeTE9Ii0yIiB4Mj0iMzUuNSIgeTI9IjE2Ii8+DQo8cmVjdCB4PSI0My42IiB5PSIxLjQiIHRyYW5zZm9ybT0ibWF0cml4KC0wLjcwNzEgMC43MDcxIC0wLjcwNzEgLTAuNzA3MSA3OC44OTI4IC0yMy44MjU1KSIgY2xhc3M9InN0NSIgd2lkdGg9IjEuNSIgaGVpZ2h0PSI2Ii8+DQo8cmVjdCB4PSI0My43IiB5PSIxLjUiIHRyYW5zZm9ybT0ibWF0cml4KC0wLjcwNzEgLTAuNzA3MSAwLjcwNzEgLTAuNzA3MSA3Mi42OTcxIDM5LjA5MzgpIiBjbGFzcz0ic3Q1IiB3aWR0aD0iMS41IiBoZWlnaHQ9IjYiLz4NCjwvc3ZnPg0K",
              "x_pos": 475.99998474121094,
              "y_pos": 246.49998474121094,
              "description": "Select or remove a subset of columns",
              "messages": [
                {
                  "id_ref": "uiOnlyField1",
                  "validation_id": "uiOnlyField1",
                  "type": "error",
                  "text": "This field cannot be empty."
                },
                {
                  "id_ref": "uiOnlyField2",
                  "validation_id": "required_uiOnlyField2_585.9274885924182",
                  "type": "error",
                  "text": "Required parameter '{label}' has no value."
                },
                {
                  "id_ref": "selected_fields",
                  "validation_id": "selected_fields",
                  "type": "error",
                  "text": "The 'Columns' field cannot be empty when the mode is 'Include'"
                }
              ],
              "ui_parameters": {
                "uiOnlyField2": [
                  "alpha",
                  "beta",
                  "gamma",
                  "delta"
                ],
                "uiOnlyField3": 23
              }
            }
          },
          "inputs": [
            {
              "id": "inPort",
              "app_data": {
                "ui_data": {
                  "cardinality": {
                    "min": 0,
                    "max": 1
                  },
                  "label": "Input Port"
                }
              }
            }
          ],
          "outputs": [
            {
              "id": "outPort",
              "app_data": {
                "ui_data": {
                  "cardinality": {
                    "min": 0,
                    "max": -1
                  },
                  "label": "Output Port"
                }
              }
            }
          ]
        }
      ],
      "app_data": {
        "ui_data": {
          "comments": []
        }
      },
      "runtime_ref": "scala-spark-2.0.1"
    }
  ],
  "schemas": [],
  "runtimes": [
    {
      "id": "scala-spark-2.0.1",
      "name": "scala-spark-2.0.1"
    }
  ]
}
